<center><h1>Tutorial for Numpy</h1></center>

For more information, visit my Portfolio at 
<a href='https://www.novypro.com/profile_projects/mohammed-dolib'>
    DashBoard & Reports Portfolio</a>
For Git Hub
<a href='https://github.com/mdolib?tab=repositories'>Mohammed Dolib Portfolio</a> or numpy documentation to discover more 
<a href='https://numpy.org/devdocs/reference/index.html'>Numpy API</a>
<center><em>Copyright Mohammed Dolib</em></center>

# Numpy library

NumPy is a Python library for working with large, multi-dimensional arrays and matrices of numerical data. It provides functions for performing mathematical operations on these arrays, as well as for performing operations on them such as sorting, reshaping, and selecting subsets of the data. NumPy is an essential library for scientific computing with Python and is widely used in machine learning, data science, and other fields. 

### Some of the key features of NumPy include:

- Functions for performing mathematical operations on arrays, such as element-wise addition, multiplication, and exponentiation.
- Tools for performing linear algebra operations on arrays, such as matrix multiplication and much more.
- Functions for generating arrays with certain properties, such as ones, zeros, and random numbers.
- Functions for reading and writing arrays to and from files, such as CSV and binary files.
- Tools for integrating NumPy with other scientific computing libraries, such as SciPy and Matplotlib.
- NumPy is an open-source library, and it is included as a standard library in many Python distributions, so you can use it without installing it separately. However, if you want to use the latest version of NumPy, you can install it using the package manager of your choice, such as pip or conda.

pip install numpy Or pip3 install numpy


### what is numpy use for
 - 1D array
 - 2D array
 - 3D array
 - Mathematics
 - Plotting
 - Machine Learning

### How normal Python list is different from Numpy
##### Python List 
- Slow.
- lots of information store in memory with list.

##### Numpy array
- Fast, 'faster to read less bytes of memory'
- No type checking when iterating through objects
- is use Contiguous memory 
- Insertion, deletion, appending, concatenation plus lots more 😎


In [2]:
# import the NumPy library into a Python script
import numpy as np

#### Basic of Numpy 

In [14]:
# 1D array
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [15]:
# 2D array
# 3D dimension array you can keep nest list inside list for it
b = np.array([[5.0,9.0,33.0],[1.0,56.0,20.0]])
b

array([[ 5.,  9., 33.],
       [ 1., 56., 20.]])

In [16]:
# get Dimension 
b.ndim

2

In [17]:
# Get Shape it will give typle (Row, Column) for one D is (N,) number of iteams
a.shape

(4,)

In [18]:
# Resahpe array 
b.reshape(3,2)

array([[ 5.,  9.],
       [33.,  1.],
       [56., 20.]])

In [36]:
# Get Data type
a.dtype
# Or you can define/specify data type from the creation of an array
x = np.array([2,4,5,6], dtype='int8')
x.dtype

dtype('int8')

In [19]:
# here is normal python list we want to Transforming to numpy array 
listpy = [1,2,3,4,5,6]
listpy

[1, 2, 3, 4, 5, 6]

In [5]:
# Checking object type it's normal python list 
type(listpy)

list

In [6]:
# Converted to Numpy array 
# this called Casting
arrnum = np.array(listpy)
arrnum

array([1, 2, 3, 4, 5, 6])

In [7]:
type(arrnum)

numpy.ndarray

In [26]:
# List nested with tuple 
_matrix =[(1,2,3),(4,5,6),(7,8,9)]
_matrix

[(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [24]:
# Numpy smart to konwo it's list of row and colmuns to converted/casting to 2D array 
mymatrix = np.array(_matrix)
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Bulitin Funcation

In [31]:
# There is building funcation & methods to work with Numpy 
# not always the case casting python data structure 

In [48]:
# up to but not inclding stoping point
np.arange(1,101,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [59]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [62]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [85]:
# It'll give us number between staring and stop point 
# as we specified on threed aregument
np.linspace(2,10,4)

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [86]:
# Idenitiy Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Random Distrbution 

In [99]:
# Random number between 0-1
np.random.rand(3)

array([0.74691055, 0.7122748 , 0.51114182])

In [174]:
# Random numral distrubation number between 0-1 luckly 
np.random.randn(3,2)

array([[-5.15868220e-04,  3.31616295e-01],
       [ 2.92578422e-01,  2.53310061e-01],
       [ 1.62716123e-01, -7.39965976e-01]])

In [200]:
_arr = np.random.randint(18,90,5)
_arr

array([57, 78, 19, 24, 52])

#### Indexing & Selection

In [69]:
# Grabbing single element

In [208]:
my_arr = np.arange(10,110,10)
my_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [209]:
my_arr[4] # Get value by index position 

50

In [221]:
my_arr[-1]

100

In [222]:
my_arr[9]

100

In [9]:
# Grabbing a slice of elements

In [218]:
my_arr[4:]

array([ 50,  60,  70,  80,  90, 100])

In [219]:
my_arr[:5]

array([10, 20, 30, 40, 50])

In [220]:
my_arr[3:8]

array([40, 50, 60, 70, 80])

In [10]:
# Broadcasting selections

In [226]:
# Here copy method make new copy of my_arr it's not reffrance to array
slice_arr = my_arr[3:8].copy()
slice_arr

array([40, 50, 60, 70, 80])

In [228]:
# Assigmnet to slice array value of 99 to entery array
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99])

In [229]:
my_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [11]:
# Indexing & selections on 2D

In [230]:
arr_2d = np.array([[15,20,25],[30,35,40],[45,50,55]])
arr_2d

array([[15, 20, 25],
       [30, 35, 40],
       [45, 50, 55]])

In [234]:
arr_2d.shape # (Row, Colmuns)

(3, 3)

In [233]:
arr_2d[0]

array([15, 20, 25])

In [232]:
arr_2d[-1]

array([45, 50, 55])

In [249]:
arr_2d[1,2]

40

In [252]:
arr_2d[2,0]

45

In [245]:
arr_2d[:3,1:2]

array([[20],
       [35],
       [50]])

In [253]:
arr_2d

array([[15, 20, 25],
       [30, 35, 40],
       [45, 50, 55]])

In [259]:
arr_2d[0:2,1:]

array([[20, 25],
       [35, 40]])

In [12]:
# Condationl selections

In [260]:
my_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [262]:
my_arr > 40

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [263]:
my_arr[my_arr > 40]

array([ 50,  60,  70,  80,  90, 100])

#### Numpy Operation & Arithmetic

Here is arithmetic between a scalar and an array

In [273]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [274]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [275]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [277]:
# Keep in mind arrays should be on the shape 
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [278]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [280]:
# Here on our array frist indexing is zero , 
# zero divide by zero mathematical speaking it doesn't make sense.
# keep in mind Numpy will do operation and replaced 
#result of nan stand for not a number and through Warning
arr / arr

C:\Users\Mohammed Dolib\AppData\Local\Temp\ipykernel_8760\2196462938.py:2: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [284]:
# Not like in python will give an error
4 / 0

ZeroDivisionError: division by zero

In [286]:
1 / arr # Example of a scalar divid by zero on first indexing on our array

C:\Users\Mohammed Dolib\AppData\Local\Temp\ipykernel_8760\1817388668.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr # Example of a scalar divid by zero on first indexing on our array


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
# Universal array funcation 
#it make our life easy you don't have to code everthing

In [287]:
arr.max()

9

In [288]:
arr.min()

0

In [289]:
arr.mean()

4.5

In [290]:
arr.std()

2.8722813232690143

In [291]:
arr.sum()

45

In [293]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [294]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [296]:
import os 
os.